In [1]:
import pandas as pd
import numpy as np

In [2]:
dt = pd.read_csv('flights.csv')
dt.head()

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0

In [3]:
#if flights in different year
dt.loc[dt['Year'] != 2013]

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [4]:
#if flights in wrong dayofweek
dt.loc[dt['DayOfWeek'] > 7]

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [5]:
#if flights in wrong dayofmonth
dt.loc[dt['DayofMonth'] > 31]

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [6]:
#if flights in wrong month
dt.loc[dt['Month'] > 31]

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [7]:
#si valeurs manquantes 
dt.isnull().sum()

Year                    0
Month                   0
DayofMonth              0
DayOfWeek               0
Carrier                 0
OriginAirportID         0
OriginAirportName       0
OriginCity              0
OriginState             0
DestAirportID           0
DestAirportName         0
DestCity                0
DestState               0
CRSDepTime              0
DepDelay                0
DepDel15             2761
CRSArrTime              0
ArrDelay                0
ArrDel15                0
Cancelled               0
dtype: int64

In [8]:
# on va regarder si wrong data dans les >15 minutes et 0 dans depdel15
condition = ((dt['DepDelay'] > 15) & (dt['DepDel15']<1))
dt.loc[condition]

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [9]:
#on va regarder les valeurs manquantes dans depdel5
dt.loc[dt['DepDel15'].isnull()]

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
171,2013,4,18,4,DL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,13930,Chicago O'Hare International,Chicago,IL,835,0,NaN,945,0,1,1
359,2013,5,22,3,OO,11433,Detroit Metro Wayne County,Detroit,MI,13930,Chicago O'Hare International,Chicago,IL,1719,0,NaN,1738,0,1,1
429,2013,7,3,3,MQ,13851,Will Rogers World,Oklahoma City,OK,13930,Chicago O'Hare International,Chicago,IL,1935,0,NaN,2125,0,1,1
545,2013,4,13,6,FL,14524,Richmond International,Richmond,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,630,0,NaN,809,0,1,1
554,2013,5,8,3,EV,12953,LaGuardia,New York,NY,11193,Cincinnati/Northern Kentucky International,Cincinnati,OH,1320,0,NaN,1524,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271410,2013,8,5,1,WN,14831,Norman Y. Mineta San Jose International,San Jose,CA,10800,Bob Hope,Burbank,CA,1525,0,NaN,1625,0,1,1
271607,2013,6,18,2,EV,14100,Philadelphia International,Philadelphia,PA,13244,Memphis International,Memphis,TN,600,0,NaN,729,0,1,1
271634,2013,5,8,3,AA,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,14100,Philadelphia International,Philadelphia,PA,1325,0,NaN,1745,0,1,1
271671,2013,10,8,2,WN,12892,Los Angeles International,Los Angeles,CA,12889,McCarran International,Las Vegas,NV,1440,0,NaN,1540,0,1,1
271885,2013,5,15,3,US,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1059,0,NaN,1918,0,1,1

In [10]:
#on a pu voir que les valeurs manquantes interviennent quand le depDelay = 0 ( pas de retard) donc depdel15 = 0
#on va d'abord confirmer ca
condition = ((dt['DepDelay'] == 0) & (dt['DepDel15']>0)) #nous affichons les valeurs avec un retard et avec un depdel15 NaN
dt.loc[condition]

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [11]:
dt

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

In [12]:
#nous pouvosn confirmer que les NaN interviennent quand ik n'y a pas de retard 
#nous allons donc modifier ces valeurs et les mettre à 0 comme il n'y a aucun retard de plus de 15mn
newdt = dt
newdt.loc[(newdt['DepDelay'] == 0), "DepDel15"] = 0
newdt.loc[dt['DepDelay'] == 0]
newdt

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

In [13]:
newdt.isnull().sum() #we have change all the naN value

Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
Carrier              0
OriginAirportID      0
OriginAirportName    0
OriginCity           0
OriginState          0
DestAirportID        0
DestAirportName      0
DestCity             0
DestState            0
CRSDepTime           0
DepDelay             0
DepDel15             0
CRSArrTime           0
ArrDelay             0
ArrDel15             0
Cancelled            0
dtype: int64

In [14]:
#the arrDelay and arrDel15 are wrong we must fix it
newdt.loc[((newdt['ArrDelay'] < 15) & (newdt['ArrDel15'] == 1))]

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
145,2013,9,12,4,MQ,11066,Port Columbus International,Columbus,OH,12478,John F. Kennedy International,New York,NY,1320,1,0.0,1515,0,1,1
171,2013,4,18,4,DL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,13930,Chicago O'Hare International,Chicago,IL,835,0,0.0,945,0,1,1
359,2013,5,22,3,OO,11433,Detroit Metro Wayne County,Detroit,MI,13930,Chicago O'Hare International,Chicago,IL,1719,0,0.0,1738,0,1,1
429,2013,7,3,3,MQ,13851,Will Rogers World,Oklahoma City,OK,13930,Chicago O'Hare International,Chicago,IL,1935,0,0.0,2125,0,1,1
545,2013,4,13,6,FL,14524,Richmond International,Richmond,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,630,0,0.0,809,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271410,2013,8,5,1,WN,14831,Norman Y. Mineta San Jose International,San Jose,CA,10800,Bob Hope,Burbank,CA,1525,0,0.0,1625,0,1,1
271607,2013,6,18,2,EV,14100,Philadelphia International,Philadelphia,PA,13244,Memphis International,Memphis,TN,600,0,0.0,729,0,1,1
271634,2013,5,8,3,AA,11298,Dallas/Fort Worth International,Dallas/Fort Worth,TX,14100,Philadelphia International,Philadelphia,PA,1325,0,0.0,1745,0,1,1
271671,2013,10,8,2,WN,12892,Los Angeles International,Los Angeles,CA,12889,McCarran International,Las Vegas,NV,1440,0,0.0,1540,0,1,1
271885,2013,5,15,3,US,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1059,0,0.0,1918,0,1,1

In [15]:
newdt.loc[((newdt['ArrDelay'] < 15) & (newdt['ArrDel15'] == 1)), "ArrDel15"] = 0 #on remplace par 0
newdt.loc[((newdt['ArrDelay'] > 15) & (newdt['ArrDel15'] != 1)), "ArrDel15"] = 1 #on remplace par 1
newdt.loc[((newdt['ArrDelay'] == 0) & (newdt['ArrDel15'] < 1))]

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
23,2013,4,19,5,AA,13204,Orlando International,Orlando,FL,13303,Miami International,Miami,FL,1405,-8,0.0,1510,0,0,0
32,2013,6,13,4,OO,14869,Salt Lake City International,Salt Lake City,UT,13198,Kansas City International,Kansas City,MO,957,2,0.0,1325,0,0,0
66,2013,5,5,7,9E,11057,Charlotte Douglas International,Charlotte,NC,13244,Memphis International,Memphis,TN,1805,-2,0.0,1846,0,0,0
115,2013,5,29,3,DL,11433,Detroit Metro Wayne County,Detroit,MI,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1015,-4,0.0,1311,0,0,0
145,2013,9,12,4,MQ,11066,Port Columbus International,Columbus,OH,12478,John F. Kennedy International,New York,NY,1320,1,0.0,1515,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271739,2013,9,4,3,US,11057,Charlotte Douglas International,Charlotte,NC,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,1150,-6,0.0,1307,0,0,0
271760,2013,4,14,7,AA,12892,Los Angeles International,Los Angeles,CA,10721,Logan International,Boston,MA,1215,21,1.0,2040,0,0,0
271772,2013,5,3,5,DL,11278,Ronald Reagan Washington National,Washington,DC,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,1000,-3,0.0,1146,0,0,0
271885,2013,5,15,3,US,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1059,0,0.0,1918,0,0,1
271932,2013,8,26,1,WN,11292,Denver International,Denver,CO,12191,William P Hobby,Houston,TX,1855,-2,0.0,2215,0,0,0

In [16]:
#maintenant on regarde si il y a des vols annulés mais avec des heures d'arrivées et de départ
newdt.loc[((newdt['DepDelay'] !=0) & (newdt['ArrDelay'] !=0) & (newdt['Cancelled'] ==1))] #aucune erreur au niveau des vols annulés

Empty DataFrame
Columns: [Year, Month, DayofMonth, DayOfWeek, Carrier, OriginAirportID, OriginAirportName, OriginCity, OriginState, DestAirportID, DestAirportName, DestCity, DestState, CRSDepTime, DepDelay, DepDel15, CRSArrTime, ArrDelay, ArrDel15, Cancelled]
Index: []

In [17]:
newdt

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

In [18]:
newdt.describe()

,Year,Month,DayofMonth,DayOfWeek,OriginAirportID,DestAirportID,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
count,271940.0,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000,271940.000000
mean,2013.0,6.978514,15.814775,3.899316,12744.899584,12739.136493,1325.498713,10.350449,0.199092,1505.477819,6.496650,0.205207,0.010723
std,0.0,1.982431,8.799033,1.987219,1501.199773,1502.569949,470.748546,35.673710,0.399318,493.204020,38.230331,0.403854,0.102995
min,2013.0,4.000000,1.000000,1.000000,10140.000000,10140.000000,1.000000,-63.000000,0.000000,1.000000,-75.000000,0.000000,0.000000
25%,2013.0,5.000000,8.000000,2.000000,11292.000000,11292.000000,920.000000,-4.000000,0.000000,1119.000000,-11.000000,0.000000,0.000000
50%,2013.0,7.000000,16.000000,4.000000,12892.000000,12892.000000,1320.000000,-1.000000,0.000000,1529.000000,-3.000000,0.000000,0.000000
75%,2013.0,9.000000,23.000000,6.000000,14057.000000,14057.000000,1725.000000,9.000000,0.000000,1918.000000,10.000000,0.000000,0.000000
max,2013.0,10.000000,31.000000,7.000000,15376.000000,15376.000000,2359.000000,1425.000000,1.000000,2359.000000,1440.000000,1.000000,1.000000

In [19]:
#What are the average (mean) departure and arrival delays?

meanDeparture = newdt.describe().iloc[1, 7]
meanArrival = newdt.describe().iloc[1, 10]

print(f"Mean of Departure delay: {meanDeparture} minutes")
print(f"Mean of Arrival delay: {meanArrival} minutes")

Mean of Departure delay: 10.350448628373906 minutes
Mean of Arrival delay: 6.496649996322718 minutes

In [20]:
#Is there a noticable difference in arrival delays for different days of the week?

test = newdt.groupby(['DayOfWeek']).describe()
test.loc[:7, ['DepDelay', 'ArrDelay']]

#As we can see, wednesday and thursday have the highest mean of delay but on saturday, 5 times less of delay than thursday

          DepDelay                                                      \
             count       mean        std   min  25%  50%   75%     max
DayOfWeek
1          41053.0  10.669647  36.501404 -24.0 -4.0 -1.0   9.0  1366.0
2          40019.0   8.585272  33.034427 -27.0 -5.0 -1.0   7.0  1386.0
3          40776.0  10.077546  36.530535 -21.0 -4.0 -1.0   8.0  1425.0
4          40656.0  13.570051  39.317015 -52.0 -4.0  0.0  13.0   737.0
5          39988.0  12.131539  37.948889 -63.0 -4.0  0.0  12.0  1281.0
6          31739.0   7.409213  31.064699 -23.0 -5.0 -1.0   6.0   831.0
7          37709.0   9.286987  33.069365 -23.0 -4.0 -1.0   8.0   977.0

          ArrDelay
             count       mean        std   min   25%  50%   75%     max
DayOfWeek
1          41053.0   6.815726  38.947995 -75.0 -11.0 -3.0  10.0  1348.0
2          40019.0   4.280567  35.546441 -68.0 -12.0 -4.0   8.0  1394.0
3          40776.0   6.998455  39.602310 -67.0 -11.0 -3.0  10.0  1440.0
4          40656.0  10.677588  41.869288 -52.0 -10.0 -1.0  14.0   745.0
5          39988.0   8.523507  40.164410 -60.0 -10.0 -2.0  12.0  1267.0
6          31739.0   2.139292  33.178588 -64.0 -13.0 -5.0   6.0   811.0
7          37709.0   4.968973  35.743924 -66.0 -12.0 -4.0   9.0   977.0

In [21]:
#Which departure airport has the highest average departure delay?

departureDelay =newdt.groupby(['OriginAirportName']).describe()
#departureDelay.sort_values(by='DepDelay')
departureDelay.iloc[:70, 56:64]

                                                   DepDelay             \
                                                      count       mean
OriginAirportName
Albuquerque International Sunport                    1827.0   8.423098
Austin - Bergstrom International                     2623.0   9.335494
Baltimore/Washington International Thurgood Mar...   5219.0  13.184901
Bob Hope                                             1447.0   6.337941
Bradley International                                1346.0   7.418276
...                                                     ...        ...
Theodore Francis Green State                          956.0   7.434100
Tucson International                                 1111.0   4.651665
Washington Dulles International                      3665.0  11.867121
Will Rogers World                                    1390.0   8.871942
William P Hobby                                      2935.0  12.757751

                                                                               \
                                                          std   min  25%  50%
OriginAirportName
Albuquerque International Sunport                   28.349601 -17.0 -4.0 -1.0
Austin - Bergstrom International                    33.132370 -17.0 -4.0  0.0
Baltimore/Washington International Thurgood Mar...  37.755225 -63.0 -3.0  1.0
Bob Hope                                            26.133683 -19.0 -4.0 -1.0
Bradley International                               32.637692 -17.0 -5.0 -2.0
...                                                       ...   ...  ...  ...
Theodore Francis Green State                        31.726628 -27.0 -5.0 -2.0
Tucson International                                32.720192 -24.0 -7.0 -3.0
Washington Dulles International                     38.719051 -19.0 -4.0 -1.0
Will Rogers World                                   37.071810 -19.0 -5.0 -2.0
William P Hobby                                     28.451592 -18.0 -2.0  3.0


                                                     75%     max
OriginAirportName
Albuquerque International Sunport                    9.0   373.0
Austin - Bergstrom International                     9.0   433.0
Baltimore/Washington International Thurgood Mar...  14.0  1172.0
Bob Hope                                             5.0   253.0
Bradley International                                6.0   356.0
...                                                  ...     ...
Theodore Francis Green State                         5.0   343.0
Tucson International                                 1.0   484.0
Washington Dulles International                      9.0   490.0
Will Rogers World                                    6.0   408.0
William P Hobby                                     16.0   357.0

[70 rows x 8 columns]

In [22]:
#Do late departures tend to result in longer arrival delays than on-time departures?

ontimeDeparture = newdt.loc[newdt['DepDelay'] <= 0] #leave early and on time
ontime = ontimeDeparture.describe().iloc[1, 10]

lateDeparture = newdt.loc[newdt['DepDelay'] >0 ] #leave lately from 1 minute
late = lateDeparture.describe().iloc[1, 10]

print(f"On time(mean): {ontime} minutes   Late(mean): {late} minutes")

#So when the departure is late, are most probably in late during the landing

On time(mean): -7.8469554033552065 minutes   Late(mean): 27.05118501221247 minutes

In [23]:
#Which route (from origin airport to destination airport) has the most late* arrivals?*

arrivalDelay =newdt.groupby(['OriginAirportName']).sum()
arrivalDelay.iloc[1,:10]
#departureDelay.sort_values(by='DepDelay')
#arrivalDelay.iloc[:70, 80:88]

Year                                                         5280099
Month                                                          18175
DayofMonth                                                     41638
DayOfWeek                                                      10278
Carrier            AAYVOOWNWNUAWNDLAAWNB6WNAAAAAAAAAAWNWNUSWNUS9E...
OriginAirportID                                             27339529
OriginCity         AustinAustinAustinAustinAustinAustinAustinAust...
OriginState        TXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTXTX...
DestAirportID                                               32505482
DestAirportName    Dallas/Fort Worth InternationalCharlotte Dougl...
Name: Austin - Bergstrom International, dtype: object

In [24]:
newdt.to_csv('cleanedFlights.csv', index=False)

In [25]:
newdt

,Year,Month,DayofMonth,DayOfWeek,Carrier,OriginAirportID,OriginAirportName,OriginCity,OriginState,DestAirportID,DestAirportName,DestCity,DestState,CRSDepTime,DepDelay,DepDel15,CRSArrTime,ArrDelay,ArrDel15,Cancelled
0,2013,9,16,1,DL,15304,Tampa International,Tampa,FL,12478,John F. Kennedy International,New York,NY,1539,4,0.0,1824,13,0,0
1,2013,9,23,1,WN,14122,Pittsburgh International,Pittsburgh,PA,13232,Chicago Midway International,Chicago,IL,710,3,0.0,740,22,1,0
2,2013,9,7,6,AS,14747,Seattle/Tacoma International,Seattle,WA,11278,Ronald Reagan Washington National,Washington,DC,810,-3,0.0,1614,-7,0,0
3,2013,7,22,1,OO,13930,Chicago O'Hare International,Chicago,IL,11042,Cleveland-Hopkins International,Cleveland,OH,804,35,1.0,1027,33,1,0
4,2013,5,16,4,DL,13931,Norfolk International,Norfolk,VA,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,545,-1,0.0,728,-9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271935,2013,9,20,5,VX,13204,Orlando International,Orlando,FL,12892,Los Angeles International,Los Angeles,CA,1730,1,0.0,1945,18,1,0
271936,2013,4,19,5,FL,10397,Hartsfield-Jackson Atlanta International,Atlanta,GA,11697,Fort Lauderdale-Hollywood International,Fort Lauderdale,FL,1020,24,1.0,1218,61,1,0
271937,2013,10,26,6,WN,12191,William P Hobby,Houston,TX,10821,Baltimore/Washington International Thurgood Ma...,Baltimore,MD,1540,30,1.0,1935,15,1,0
271938,2013,5,7,2,HA,13830,Kahului Airport,Kahului,HI,12173,Honolulu International,Honolulu,HI,609,-5,0.0,641,-6,0,0
271939,2013,6,11,2,UA,14771,San Francisco International,San Francisco,CA,14100,Philadelphia International,Philadelphia,PA,1338,60,1.0,2200,40,1,0

In [26]:
dt.dtypes

Year                   int64
Month                  int64
DayofMonth             int64
DayOfWeek              int64
Carrier               object
OriginAirportID        int64
OriginAirportName     object
OriginCity            object
OriginState           object
DestAirportID          int64
DestAirportName       object
DestCity              object
DestState             object
CRSDepTime             int64
DepDelay               int64
DepDel15             float64
CRSArrTime             int64
ArrDelay               int64
ArrDel15               int64
Cancelled              int64
dtype: object